name: Deploy to Render

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
      - gh-actions-gradle

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Clear the Gradle cache
      - name: Clear Gradle cache
        run: rm -rf $HOME/.gradle/caches

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: backend/WarehouseInterface

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to the Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -f backend/WarehouseInterface/Dockerfile -t myapp:latest backend/WarehouseInterface
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # deploy to render if docker succeeded
      - name: Deploy to render
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "$deploy_url")
          echo "Deployment response: $response"
          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code: $response"
            exit 1
          fi
